# Generated by Django 4.2.11 on 2026-06-09 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_name", models.CharField(max_length=255)),
                ("test_type", models.CharField(max_length=100)),
                (
                    "sample_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("test_date", models.DateField(blank=True, null=True)),
                ("lab_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "result_value",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "standard_value",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_tests",
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaterialRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_name", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit", models.CharField(max_length=50)),
                ("requested_date", models.DateField(auto_now_add=True)),
                ("required_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("DELIVERED", "Delivered"),
                            ("RECEIVED", "Received"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_requests",
                        to="core.project",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterimPaymentCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ipc_number", models.CharField(max_length=100)),
                (
                    "claimed_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "verified_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "certified_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Certificate"),
                            ("CERTIFIED", "Certified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("certified_date", models.DateField(blank=True, null=True)),
                (
                    "certified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ipcs",
                        to="core.invoice",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ipcs",
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BIMModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
                (
                    "discipline",
                    models.CharField(
                        choices=[
                            ("ARCH", "Architectural"),
                            ("STRUCT", "Structural"),
                            ("MEP", "MEP"),
                            ("INFRA", "Infrastructure"),
                            ("LANDSCAPE", "Landscape"),
                        ],
                        max_length=20,
                    ),
                ),
                ("lod_level", models.CharField(default="LOD 300", max_length=50)),
                ("version", models.CharField(default="v1.0", max_length=50)),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WIP", "Work In Progress"),
                            ("REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                        ],
                        default="WIP",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bim_models",
                        to="core.project",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BIMClash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clash_type", models.CharField(default="HARD", max_length=50)),
                ("description", models.TextField()),
                ("discipline_a", models.CharField(max_length=50)),
                ("discipline_b", models.CharField(max_length=50)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_REVIEW", "In Review"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("detected_date", models.DateField(blank=True, null=True)),
                ("resolved_date", models.DateField(blank=True, null=True)),
                (
                    "bim_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clashes",
                        to="core.bimmodel",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bim_clashes",
                        to="core.project",
                    ),
                ),
            ],
        ),
    ]
