# Generated by Django 4.2.11 on 2026-06-18 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_materialtest_materialrequest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("m", "Meter (m)"),
                            ("m2", "Meter Persegi (m²)"),
                            ("m3", "Meter Kubik (m³)"),
                            ("kg", "Kilogram (kg)"),
                            ("ton", "Ton"),
                            ("unit", "Unit"),
                            ("pcs", "Pieces"),
                            ("ltr", "Liter (ltr)"),
                            ("sak", "Sak"),
                            ("roll", "Roll"),
                            ("ls", "Lump Sum"),
                        ],
                        default="unit",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("STRUKTUR", "Struktur (Besi, Beton, dll)"),
                            ("FINISHING", "Finishing (Cat, Plester, dll)"),
                            ("MEP", "MEP (Listrik, Plumbing, AC)"),
                            ("ALAT", "Alat & Perkakas"),
                            ("LAIN", "Lain-lain"),
                        ],
                        default="LAIN",
                        max_length=20,
                    ),
                ),
                (
                    "minimum_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Batas stok minimum sebelum notifikasi",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_items",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
                "unique_together": {("project", "item_code")},
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("IN", "Material Masuk (Delivery)"),
                            ("OUT", "Material Keluar (Usage)"),
                            ("ADJUST", "Penyesuaian Stok (Adjustment)"),
                            ("RETURN", "Return ke Supplier"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="No. Surat Jalan / DO / PO",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Lokasi penggunaan / gudang",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("transaction_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "material_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.materialitem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_transactions",
                        to="core.project",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
    ]
