# Generated by Django 4.2.11 on 2026-06-20 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_materialitem_stocktransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("HQ_DIRECTOR", "HQ Director"),
                    ("PROJECT_DIRECTOR", "Project Director"),
                    ("FINANCE_HQ", "Finance HQ"),
                    ("DOC_CONTROLLER", "Document Controller"),
                    ("ADMIN_SYSTEM", "Admin System"),
                    ("PROJECT_MANAGER", "Project Manager"),
                    ("SITE_ENGINEER", "Site Engineer"),
                    ("SUPERVISOR", "Supervisor"),
                    ("COST_ENGINEER", "Cost Engineer / QS"),
                    ("HSE_OFFICER", "Safety Officer (HSE)"),
                    ("STOREKEEPER", "Storekeeper"),
                    ("ADMIN_SITE", "Admin Site"),
                    ("QA_QC", "QA/QC Engineer"),
                    ("BIM_MANAGER", "BIM Manager"),
                    ("ENV_SPECIALIST", "Environmental Specialist"),
                    ("CONSULTANT", "Consultant"),
                    ("CLIENT", "Client / Owner"),
                ],
                default="SITE_ENGINEER",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="SiteInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("si_number", models.CharField(max_length=100, unique=True)),
                ("subject", models.CharField(max_length=255)),
                ("instruction", models.TextField()),
                ("issued_date", models.DateField(auto_now_add=True)),
                ("issued_to", models.CharField(max_length=255)),
                ("acknowledged_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("IMPLEMENTED", "Implemented"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="si_acknowledged",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="si_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_instructions",
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RFI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rfi_number", models.CharField(max_length=100, unique=True)),
                ("subject", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("raised_date", models.DateField(auto_now_add=True)),
                ("response", models.TextField(blank=True, null=True)),
                ("response_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("IN_REVIEW", "In Review"),
                            ("RESPONDED", "Responded"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rfis_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfis",
                        to="core.project",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rfis_raised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NCR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ncr_number", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("reported_date", models.DateField(auto_now_add=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor"),
                            ("MAJOR", "Major"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MAJOR",
                        max_length=20,
                    ),
                ),
                ("root_cause", models.TextField(blank=True, null=True)),
                ("corrective_action", models.TextField(blank=True, null=True)),
                ("corrective_action_date", models.DateField(blank=True, null=True)),
                ("verified_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("CORRECTIVE_ACTION", "Corrective Action"),
                            ("VERIFIED", "Verified"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ncrs",
                        to="core.project",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ncrs_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ncrs_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
