# Generated by Django 4.2.11 on 2026-06-20 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_alter_userprofile_role_siteinstruction_rfi_ncr"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manpower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nik", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("WORKER", "Pekerja Lapangan"),
                            ("FOREMAN", "Mandor"),
                            ("OPERATOR", "Operator Alat"),
                            ("TECHNICIAN", "Teknisi"),
                            ("ADMIN", "Admin Lapangan"),
                            ("OTHER", "Lainnya"),
                        ],
                        default="WORKER",
                        max_length=50,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("join_date", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="manpower_photos/"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manpowers",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("check_in", models.TimeField(blank=True, null=True)),
                ("check_out", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Hadir"),
                            ("ABSENT", "Tidak Hadir"),
                            ("SICK", "Sakit"),
                            ("LEAVE", "Izin/Cuti"),
                            ("LATE", "Terlambat"),
                        ],
                        default="PRESENT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manpower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="core.manpower",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="core.project",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "unique_together": {("manpower", "date")},
            },
        ),
    ]
