# Generated by Django 4.2.11 on 2026-06-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_equipment_notification_equipmentusage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("CONTRACTOR", "Kontraktor"),
                    ("CONSULTANT", "Konsultan"),
                    ("CLIENT", "Klien"),
                    ("VENDOR", "Vendor"),
                    ("SUBCONTRACTOR", "Subkontraktor"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_code", models.CharField(max_length=100, unique=True)),
                (
                    "material_types",
                    models.TextField(
                        blank=True,
                        help_text="Jenis material yang disediakan",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        limit_choices_to={"company_type": "VENDOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendors",
                        to="core.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subcontractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subcontractor_code", models.CharField(max_length=100, unique=True)),
                (
                    "specialization",
                    models.TextField(
                        blank=True, help_text="Spesialisasi pekerjaan", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        limit_choices_to={"company_type": "SUBCONTRACTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontractors",
                        to="core.company",
                    ),
                ),
            ],
        ),
    ]
