# Generated by Django 5.2.15 on 2026-07-10 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_dailyreportdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="consultant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultant_projects",
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="contractor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contractor_projects",
                to="core.company",
            ),
        ),
        migrations.CreateModel(
            name="ProjectReadinessChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contractor_assigned", models.BooleanField(default=False)),
                ("consultant_assigned", models.BooleanField(default=False)),
                ("team_assigned", models.BooleanField(default=False)),
                ("budget_set", models.BooleanField(default=False)),
                ("timeline_set", models.BooleanField(default=False)),
                ("baseline_created", models.BooleanField(default=False)),
                ("boq_imported", models.BooleanField(default=False)),
                ("ready", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readiness",
                        to="core.project",
                    ),
                ),
            ],
        ),
    ]
