# Generated by Django 5.2.15 on 2026-07-10 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_dailyreportequipmentusage_dailyreportmanpowerusage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReportWorkProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actual_quantity",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "item_progress_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "project_progress_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "daily_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_progress_items",
                        to="core.dailyreport",
                    ),
                ),
                (
                    "work_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_report_progress_items",
                        to="core.workitem",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
