# Generated by Django 5.2.15 on 2026-07-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_dailyreportworkprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Review"),
                    ("VERIFIED", "Verified"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
