# Generated by Django 5.2.15 on 2026-07-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_invoice_approved_at_invoice_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("HQ_DIRECTOR", "HQ Director"),
                    ("PROJECT_DIRECTOR", "Project Director"),
                    ("FINANCE_HQ", "Finance HQ"),
                    ("FINANCE_SITE", "Finance Site"),
                    ("DOC_CONTROLLER", "Document Controller"),
                    ("ADMIN_SYSTEM", "Admin System"),
                    ("PROJECT_MANAGER", "Project Manager"),
                    ("SITE_ENGINEER", "Site Engineer"),
                    ("SUPERVISOR", "Supervisor"),
                    ("COST_ENGINEER", "Cost Engineer / QS"),
                    ("HSE_OFFICER", "Safety Officer (HSE)"),
                    ("STOREKEEPER", "Storekeeper"),
                    ("ADMIN_SITE", "Admin Site"),
                    ("QA_QC", "QA/QC Engineer"),
                    ("BIM_MANAGER", "BIM Manager"),
                    ("ENV_SPECIALIST", "Environmental Specialist"),
                    ("CONSULTANT", "Consultant"),
                    ("CLIENT", "Client / Owner"),
                ],
                default="SITE_ENGINEER",
                max_length=30,
            ),
        ),
    ]
