# Generated by Django 5.2.15 on 2026-07-11 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_approval_consultant_at_approval_consultant_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("HQ_DIRECTOR", "HQ Director"),
                    ("PROJECT_DIRECTOR", "Project Director"),
                    ("FINANCE_HQ", "Finance HQ"),
                    ("FINANCE_SITE", "Finance Site"),
                    ("DOC_CONTROLLER", "Document Controller"),
                    ("ADMIN_SYSTEM", "Admin System"),
                    ("PROJECT_MANAGER", "Project Manager"),
                    ("SITE_ENGINEER", "Site Engineer"),
                    ("SUPERVISOR", "Supervisor"),
                    ("COST_ENGINEER", "Cost Engineer / QS"),
                    ("HSE_OFFICER", "Safety Officer (HSE)"),
                    ("STOREKEEPER", "Storekeeper"),
                    ("LOGISTICS", "Logistics Officer"),
                    ("ADMIN_SITE", "Admin Site"),
                    ("QA_QC", "QA/QC Engineer"),
                    ("BIM_MANAGER", "BIM Manager"),
                    ("ENV_SPECIALIST", "Environmental Specialist"),
                    ("CONSULTANT", "Consultant"),
                    ("CLIENT", "Client / Owner"),
                ],
                default="SITE_ENGINEER",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="LogisticsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("DELIVERY_TRACKING", "Delivery Tracking"),
                            ("MATERIAL_RECEIVING", "Material Receiving"),
                            ("STOCK_ISSUE", "Stock Issue to Site"),
                            ("STOCK_RETURN", "Return to Supplier"),
                            ("STOCK_TRANSFER", "Transfer Material"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("ON_DELIVERY", "On Delivery"),
                            ("RECEIVED", "Received"),
                            ("ISSUED", "Issued"),
                            ("RETURNED", "Returned"),
                            ("TRANSFERRED", "Transferred"),
                            ("DAMAGED", "Damaged / Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "from_location",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "to_location",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("GOOD", "Good"),
                            ("PARTIAL", "Partial"),
                            ("DAMAGED", "Damaged"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="GOOD",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("actual_date", models.DateField(blank=True, null=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="logistics_documents/%Y/%m/"
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logistics_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logistics_records",
                        to="core.materialitem",
                    ),
                ),
                (
                    "material_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logistics_records",
                        to="core.materialrequest",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logistics_records",
                        to="core.project",
                    ),
                ),
                (
                    "stock_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logistics_records",
                        to="core.stocktransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-actual_date", "-created_at"],
            },
        ),
    ]
