# Generated by Django 5.2.15 on 2026-07-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_userprofile_role_logisticsrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hsereport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily"),
                    ("INCIDENT", "Incident"),
                    ("NEAR_MISS", "Near Miss"),
                    ("UNSAFE_ACT", "Unsafe Act"),
                    ("UNSAFE_CONDITION", "Unsafe Condition"),
                    ("AUDIT", "Audit"),
                ],
                default="DAILY",
                max_length=20,
            ),
        ),
    ]
