# Generated by Django 5.2.15 on 2026-07-13 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_hsereport_report_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Present"),
                    ("ABSENT", "Absent"),
                    ("SICK", "Sick"),
                    ("LEAVE", "Leave"),
                    ("LATE", "Late"),
                ],
                default="PRESENT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="category",
            field=models.CharField(
                choices=[
                    ("EXCAVATOR", "Excavator"),
                    ("BULLDOZER", "Bulldozer"),
                    ("CRANE", "Crane"),
                    ("CONCRETE_MIXER", "Concrete Mixer"),
                    ("COMPACTOR", "Compactor"),
                    ("TRUCK", "Truck"),
                    ("GENERATOR", "Generator"),
                    ("WELDING", "Welding Machine"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("MAINTENANCE", "Under Maintenance"),
                    ("REPAIR", "Under Repair"),
                    ("RENTED", "Rented"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="equipmentmaintenance",
            name="maintenance_type",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled Maintenance"),
                    ("UNSCHEDULED", "Unscheduled Maintenance"),
                    ("REPAIR", "Repair"),
                    ("OVERHAUL", "Overhaul"),
                ],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="equipmentmaintenance",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="manpower",
            name="role",
            field=models.CharField(
                choices=[
                    ("WORKER", "Field Worker"),
                    ("FOREMAN", "Foreman"),
                    ("OPERATOR", "Equipment Operator"),
                    ("TECHNICIAN", "Technician"),
                    ("ADMIN", "Site Admin"),
                    ("OTHER", "Other"),
                ],
                default="WORKER",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="materialitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("STRUKTUR", "Structure"),
                    ("FINISHING", "Finishing"),
                    ("MEP", "MEP"),
                    ("ALAT", "Tools & Equipment"),
                    ("LAIN", "Other"),
                ],
                default="LAIN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="materialitem",
            name="minimum_stock",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Minimum stock threshold before notification",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="materialitem",
            name="unit",
            field=models.CharField(
                choices=[
                    ("m", "Meter (m)"),
                    ("m2", "Square Meter (m2)"),
                    ("m3", "Cubic Meter (m3)"),
                    ("kg", "Kilogram (kg)"),
                    ("ton", "Ton"),
                    ("unit", "Unit"),
                    ("pcs", "Pieces"),
                    ("ltr", "Liter (ltr)"),
                    ("sak", "Sak"),
                    ("roll", "Roll"),
                    ("ls", "Lump Sum"),
                ],
                default="unit",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("INFO", "Info"),
                    ("WARNING", "Warning"),
                    ("SUCCESS", "Success"),
                    ("ALERT", "Important Alert"),
                ],
                default="INFO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[("UNREAD", "Unread"), ("READ", "Read")],
                default="UNREAD",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Usage location / warehouse",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="reference_number",
            field=models.CharField(
                blank=True,
                help_text="Delivery Note / DO / PO No.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("IN", "Material In (Delivery)"),
                    ("OUT", "Material Out (Usage)"),
                    ("ADJUST", "Stock Adjustment"),
                    ("RETURN", "Return to Supplier"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="RoleReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reporter_role",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("report_type", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("REVIEWED", "Reviewed"),
                            ("CLOSED", "Closed"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("report_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_reports",
                        to="core.project",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date", "-created_at"],
            },
        ),
    ]
