# Generated by Django 4.2.11 on 2026-07-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_attendance_status_alter_equipment_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemProgressReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        default="Progress Report Church Iliomar Versi 1.xlsx",
                        max_length=255,
                    ),
                ),
                (
                    "source_sheet",
                    models.CharField(
                        default="Construction Progress Report", max_length=255
                    ),
                ),
                ("source_row", models.PositiveIntegerField()),
                ("item_no", models.PositiveIntegerField(blank=True, null=True)),
                ("activity", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "progress_percent",
                    models.DecimalField(decimal_places=3, default=0, max_digits=7),
                ),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("photo_note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["source_row"],
                "unique_together": {("source_name", "source_sheet", "source_row")},
            },
        ),
    ]
