# Generated by Django 4.2.11 on 2026-07-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_itemprogressreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemprogressreport",
            name="photos",
            field=models.ManyToManyField(
                blank=True, related_name="item_reports", to="core.progressphoto"
            ),
        ),
    ]
