# Generated by Django 4.2.11 on 2026-07-15 13:52

from django.db import migrations, models
import django.db.models.deletion


def assign_existing_item_reports_to_first_project(apps, schema_editor):
    Project = apps.get_model("core", "Project")
    ItemProgressReport = apps.get_model("core", "ItemProgressReport")
    project = Project.objects.order_by("id").first()
    if project:
        ItemProgressReport.objects.filter(project__isnull=True).update(project=project)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_itemprogress_photos_m2m"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="itemprogressreport",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="itemprogressreport",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_progress_reports",
                to="core.project",
            ),
        ),
        migrations.RunPython(assign_existing_item_reports_to_first_project, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="itemprogressreport",
            unique_together={("project", "source_name", "source_sheet", "source_row")},
        ),
    ]
