from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard_view, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('switch-role/', views.switch_role, name='switch_role'),
    path('reports/submit/', views.submit_report, name='submit_report'),
    path('reports/<int:report_id>/approve/', views.approve_report, name='approve_report'),
    path('reports/<int:report_id>/resubmit/', views.resubmit_report, name='resubmit_report'),
    path('reports/print/', views.print_report, name='print_report'),
    path('daily-report/<int:report_id>/', views.daily_report_detail_view, name='daily_report_detail'),
    path('reports/export/', views.export_report_excel, name='export_report_excel'),
    path('projects/create/', views.create_project, name='create_project'),
    path('projects/<int:project_id>/update/', views.update_project, name='update_project'),
    path('vo/submit/', views.submit_vo, name='submit_vo'),
    path('vo/<int:vo_id>/approve/', views.approve_vo, name='approve_vo'),
    path('hse/incident/submit/', views.submit_hse_incident, name='submit_hse_incident'),
    path('material/request/submit/', views.submit_material_request, name='submit_material_request'),
    path('material/request/<int:request_id>/review/', views.review_material_request, name='review_material_request'),
    path('material/request/<int:request_id>/deliver/', views.deliver_material_request, name='deliver_material_request'),
    path('material/request/<int:request_id>/receive/', views.receive_material_request, name='receive_material_request'),
    path('material/waste/record/', views.record_material_waste, name='record_material_waste'),
    path('logistics/record/submit/', views.submit_logistics_record, name='submit_logistics_record'),
    path('purchase/request/submit/', views.submit_purchase_request, name='submit_purchase_request'),
    path('bim/clash/submit/', views.submit_bim_clash, name='submit_bim_clash'),
    path('boq/import/', views.import_boq_excel, name='import_boq_excel'),
    path('progress/import-csv/', views.import_progress_csv, name='import_progress_csv'),
    path('item-report/submit/', views.submit_item_progress_report, name='submit_item_report'),
    path('item-report/<int:item_id>/update/', views.update_item_progress_report, name='update_item_report'),
    path('item-report/<int:item_id>/delete/', views.delete_item_progress_report, name='delete_item_report'),
    path('api/daily-report-photos/', views.get_daily_report_photos, name='api_daily_report_photos'),
    path('approvals/<int:approval_id>/process/', views.process_approval, name='process_approval'),
    path('invoices/submit/', views.submit_invoice, name='submit_invoice'),
    path('invoices/<int:invoice_id>/review/', views.review_invoice, name='review_invoice'),
    path('invoices/<int:invoice_id>/paid/', views.mark_invoice_paid, name='mark_invoice_paid'),
    path('financial/submit/', views.submit_financial_record, name='submit_financial_record'),
    path('financial/<int:record_id>/review/', views.review_financial_record, name='review_financial_record'),
    path('financial/<int:record_id>/paid/', views.mark_financial_record_paid, name='mark_financial_record_paid'),
    path('documents/submit/', views.submit_document, name='submit_document'),
    path('documents/<int:doc_id>/review/', views.review_document, name='review_document'),
    path('documents/<int:doc_id>/approve/', views.approve_document, name='approve_document'),
    path('meetings/submit/', views.submit_meeting, name='submit_meeting'),
    # Inventory / Stock Management
    path('inventory/item/add/', views.add_material_item, name='add_material_item'),
    path('inventory/transaction/record/', views.record_stock_transaction, name='record_stock_transaction'),
    # Manpower & Attendance
    path('manpower/', views.manpower_view, name='manpower'),
    path('manpower/add/', views.add_manpower, name='add_manpower'),
    path('attendance/', views.attendance_view, name='attendance'),
    path('attendance/record/', views.record_attendance, name='record_attendance'),
    # Equipment Management
    path('equipment/', views.equipment_view, name='equipment'),
    path('equipment/add/', views.add_equipment, name='add_equipment'),
    path('equipment/usage/record/', views.record_equipment_usage, name='record_equipment_usage'),
    path('equipment/maintenance/record/', views.record_equipment_maintenance, name='record_equipment_maintenance'),
    # Notifications
    path('notifications/', views.notifications_view, name='notifications'),
    path('notifications/<int:notification_id>/read/', views.mark_notification_read, name='mark_notification_read'),
    # Exporting
    path('export/manpower/', views.export_manpower, name='export_manpower'),
    path('export/attendance/', views.export_attendance, name='export_attendance'),
    path('export/equipment/', views.export_equipment, name='export_equipment'),
    path('export/daily-reports/', views.export_daily_reports, name='export_daily_reports'),
    path('export/cost-summaries/', views.export_cost_summaries, name='export_cost_summaries'),
    path('export/financial-records/', views.export_financial_records, name='export_financial_records'),
    path('export/material-items/', views.export_material_items, name='export_material_items'),
    path('export/material-control/', views.export_material_control, name='export_material_control'),
    path('export/logistics/', views.export_logistics_records, name='export_logistics_records'),
    # Schedule & Gantt Chart
    path('schedule/', views.schedule_view, name='schedule'),
    path('schedule/add/', views.add_schedule, name='add_schedule'),
    path('schedule/<int:schedule_id>/update/', views.update_schedule_progress, name='update_schedule_progress'),
    # Internal Chat
    path('chat/', views.chat_view, name='chat'),
    path('chat/create_room/', views.create_chat_room, name='create_chat_room'),
]
